{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-backend
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- if .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuerRef.name }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.hosts.backend.host }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.backend.host }}
      secretName: {{ .Values.ingress.tls.secretName }}-backend
  {{- end }}
  rules:
    {{- with .Values.ingress.hosts.backend }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.backend.name }}
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- if .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuerRef.name }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.hosts.frontend.host }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.frontend.host }}
      secretName: {{ .Values.ingress.tls.secretName }}-frontend
  {{- end }}
  rules:
    {{- with .Values.ingress.hosts.frontend }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.frontend.name }}
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
    {{- end }}
{{- end }} 